#!/usr/bin/env bash

set -e

# Get the script's directory
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Define the path to the AUTHORS file in the script's directory
AUTHORS_FILE="${SCRIPTDIR}/AUTHORS"

# Generate the AUTHORS file content
{
	    echo "# File @generated by generate-authors.sh. DO NOT EDIT."
	        echo "# This file lists all contributors to the repository."
		    echo "# See generate-authors.sh to make modifications."
		        echo
			    git -C "$SCRIPTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf
		    } > "$AUTHORS_FILE"

	    echo "AUTHORS file has been generated at: $AUTHORS_FILE"

